version: '3'
services:
  web:
    build:
      context: ./web
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-file.sql
    #  - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
